name: Build & Deploy page

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy page
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun i

      - name: Build web page
        run: bun run build

      # https://github.com/marketplace/actions/github-pages-action
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: aigis2022.flandre.tw
