name: Build & Deploy page

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy page
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/cache
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      # https://github.com/marketplace/actions/setup-pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.4
          run_install: true

      - name: Build web page
        run: pnpm build

      # https://github.com/marketplace/actions/github-pages-action
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: aigis2022.flandre.tw
